require 'zeitwerk'

loader = Zeitwerk::Loader.new
loader.push_dir("src")
loader.setup

require 'colorize'
require 'unicode/emoji'
require 'httparty'
require 'pry'
require 'openai_chatgpt'
require 'dotenv/load'
require_relative 'dice_roller'
require_relative 'adventures/adventure_part'
require_relative 'adventures/timer'
require_relative 'adventures/advantage'
require_relative 'adventures/backstory'
require_relative 'adventures/challenge'
require_relative 'adventures/reward'
require_relative 'adventures/person'
require_relative 'adventures/item'
require_relative 'adventures/adjective'
require_relative 'adventures/clue'
require_relative 'adventures/motivation'
require_relative 'adventures/caller'
require_relative 'factions/faction_part'
require_relative 'factions/name'
require_relative 'factions/type'
require_relative 'factions/motivation'
require_relative 'factions/reputation'
require_relative 'factions/stability'
require_relative 'factions/methods'
require_relative 'factions/age'
require_relative 'factions/leader'
require_relative 'factions/joining'
require_relative 'factions/influence'
require_relative 'encounters/encounter'
require_relative 'encounters/npc'
require_relative 'encounters/animal_herd'
require_relative 'encounters/wandering_monster'
require_relative 'encounters/lair'
require_relative 'encounters/remote_structure'
require_relative 'encounters/ruined_stucture'
require_relative 'encounters/past_event'
require_relative 'encounters/current_event'
require_relative 'encounters/lost_item'
require_relative 'encounters/natural_structure'
require_relative 'encounters/remarkable_feature'
require_relative 'names/name'
require_relative 'names/weapon_name'
require_relative 'names/faction_name'
require_relative 'dungeons/type'
require_relative 'dungeons/name'
require_relative 'dungeons/description'
require_relative 'clients/chatgpt'